<?php

$I = new \AcceptanceTester\SpringboardSteps($scenario);
$I->wantTo('Enable and test Springboard Tags');

// We need a unique title so we can pick it from the template list.
$title = 'Form layouts test ' . time();

$I->am('admin');
$I->login();
$I->enableModule('Springboard Tag');
$I->amOnPage('admin/people/permissions');
$I->checkOption('#edit-4-administer-springboard-tags');
$I->amOnPage('springboard/rebuild-sb-menu');
$I->click('Rebuild');
$I->moveMouseOver('.marketinganalytics');
$I->see('Tags');
$I->amOnPage('springboard/springboard-tags');
$I->see('General Datalayer');
$I->click('Edit');
$I->click('Save');
$I->see('Overridden');
$I->click('.ctools-link');
$I->click('Revert');
$I->click('Revert');
$I->dontSee('Overridden');
$I->click('.ctools-link');
$I->click('Enable');
$I->waitForElement('.ctools-export-ui-enabled', 5);
$I->click('.ctools-link');
$I->click('Disable');
$I->wait(2);
$I->dontSeeElement('.ctools-export-ui-enabled');
$I->click('Add');
$I->fillField('#edit-admin-title', 'Administrative title');
$I->fillField('#edit-admin-description', 'Administrative description');
$I->fillField('#edit-tag', '<script language="Martian">Grok</script>');
$I->click("Save");
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//body/script[@language="Martian"]');
$I->click('Edit');
$I->selectOption('#edit-placement', 'In the head tag');
$I->click("Save");
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//head/script[@language="Martian"]');
$I->click('Edit');
$I->selectOption('#edit-placement', 'Main content');
$I->click("Save");
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//div[@id="main"]//script[@language="Martian"]');
$I->logout();
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//div[@id="main"]//script[@language="Martian"]');
$I->am('admin');
$I->login();
$I->amOnPage('springboard/springboard-tags');
$I->click('Edit');
$I->selectOption('#edit-placement', 'In the head tag');
$I->click("Save");
$I->logout();
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//head/script[@language="Martian"]');
$I->am('admin');
$I->login();
$I->amOnPage('springboard/springboard-tags');
$I->click('Edit');
$I->selectOption('#edit-placement', 'In the head tag');
$I->click("Save");
$I->logout();
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//head/script[@language="Martian"]');
$I->amOnPage('springboard/springboard-tags');
$I->see('Access Denied');
$I->am('admin');
$I->login();
$I->createUser('testuser', 'testeruser@example.com', '4');
$I->logout();
$I->am('testuser');
$I->login();
$I->amOnPage('springboard/springboard-tags');
$I->dontSee('Access Denied');
$I->click("Edit");
$I->click('Fundraiser Visibility');
$I->checkOption('#edit-visibility-fundraiser-confirmation');
$I->click('Content Visibility');
$I->checkOption('#edit-visibility-node-type-donation-form');
$I->click("Save");
$I->click('Donation Forms');
$I->click("view");
$I->makeADonation();
$I->seeInSource('<script language="Martian">Grok</script>');
$I->seeElementInDOM('//head/script[@language="Martian"]');


